{{- if and .Values.feedScraper.enabled .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "jasper.fullname" . }}-feed-scraper
  labels:
    {{- include "jasper.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "jasper.fullname" . }}-feed-scraper
  minReplicas: {{ .Values.feedScraper.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.feedScraper.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.feedScraper.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.feedScraper.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.feedScraper.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.feedScraper.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
