apiVersion: v1
kind: Secret
metadata:
  name: jasper-jwt-config
type: Opaque
data:
{{- if .Values.config.override.security.clientSecret }}
  override: {{ .Values.config.override.security.clientSecret | b64enc }}
{{- end }}
