{{- if .Values.config.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: jasper-jwt-config
type: Opaque
data:
  clientSecret: {{ .Values.config.clientSecret | b64enc | b64enc }}
{{- end }}
