{{ if .Values.smtp.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "jasper.fullname" . }}-smtp
  labels:
    {{- include "jasper.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 25
      targetPort: smtp
      protocol: TCP
      name: smtp
  selector:
    {{- include "jasper.selectorLabels" . | nindent 4 }}
{{ end }}
